const ProductActionTypes = {
  GET_PRODUCT_START: "GET_PRODUCT_START",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE"
};

export default ProductActionTypes;